### ISSUE TITLE
Github Label 에 대한 논의

### ISSUE THREAD

**Issue by YooYoungmo** [YooYoungmo/AEP#10]
먼저 생각해 볼 수 있는 것은 Label 이 정말 필요한가? 입니다. 꼭 필요 없다면 불필요한 오해를 발생 시킬 수 있으니 차라리 안 쓰는게 좋을 것 같습니다.

현재 학습하고자 하는 부분은 Github이 주가 아니니까요. 
선택과 집중이 필요할 듯 합니다.

**Comment by LangVE** [comment]
생각 잘들었습니다. 생각 정리해서 코멘트 달도록 하겠습니다.

**Comment by LangVE** [comment]
close 된 내용을 reopen 해봅니다..

디폴트로 등록된 Label을 두 가지 타입으로 나눠 볼 수 있겠습니다.

* issue 등록시 사용
* issue Close 시 사용 

### issue 등록시 사용  
  * enhancement : 기능 추가(, 개선, 리펙토링)
  * bug : 버그.
  * question : 질문.
  * help wanted : 도움 요청.

### issue Close 시 사용  
  * duplicate : 다른 issue와 중복하고 있다. 원본에 링크를 남기고 close.
  * invalid : 잘못된 issue. 잘못된 이유를 코멘트 남기고 close.
  * wontfix : 굳이 대응하지 않는다. 대응하지 않는 이유를 쓰고 close.

의견있으시면 달아 주세요.
괜찮으시면 위와 같이 사용했으면 합니다.

**Comment by LangVE** [comment]
참고 : http://jacking.tistory.com/1424

**Comment by LangVE** [comment]
참고 Github API

https://developer.github.com/v3/issues/

**Comment by YooYoungmo** [comment]
일단 저에게 대안이 없고 프로젝트에서 달성 하고자 하는 본질은 아니기 때문에 의견에 따르겠습니다.

**Comment by YooYoungmo** [comment]
불필요한 논의를 방지하기 위해 이슈를 Close 합니다.
