### ISSUE TITLE
Disk IO 를 줄이기-싱글톤 구현하기

### ISSUE THREAD

**Issue by YooYoungmo** [YooYoungmo/AEP#16]

**Comment by YooYoungmo** [comment]
제목 변경

**Comment by YooYoungmo** [comment]
제목 변경

**Comment by YooYoungmo** [comment]
싱글톤 설계 클래스 다이어그램 -  http://yuml.me/edit/5d8bdba4
![5d8bdba4](https://cloud.githubusercontent.com/assets/16472109/22449798/ace9d1b8-e7a5-11e6-9bce-b2e4ca749178.png)

이렇게 설계되면 AppConfig 사용법이 아래 처럼 변경됨
```java
AppConfig appConfig = AppConfig.getInstance();
Map<String, String> configMap = appConfig .get("paymentGateway");
String domain = configMap.get("domain");
String propertyPath = configMap.get("propertyPath")
```

**Comment by YooYoungmo** [comment]
위의 식으로 싱글톤을 구현 하게 되면 예상 되는 단점으로는 AppConfig 사용성 측면에서 
```java
AppConfig appConfig = AppConfig.getInstance();
```
해야 하는 불편함(?)이 따름

하지만 이러한 불편함은 현재로써는 감내해야하는 포인트로 생각되고,
이를 개선하는 방법으로는 Spring Framework 처럼 Dependency Injection 을 통해 복잡성을 줄여야 함.

**Comment by YooYoungmo** [comment]
다른 대안으로는 싱글톤 객체를 브릿지로 사용할 수 있음.
![4bb4bb9b](https://cloud.githubusercontent.com/assets/16472109/22450020/36c51b26-e7a7-11e6-8d9f-679d595805c6.png)

이렇게 되면  AppConfig 사용법은 변경 되지 않음.

**Comment by LangVE** [comment]
제가 생각한 부분까지 정리해서 올립니다.
AppConfigFileLoader 자체를 변경하는 것으로 생각을 해보았습니다.
AppConfig.getConfigMap() 내부에서 호출 하는 사용법은 아래와 같이 바뀝니다.

![aep-uml-appconfigfileloader_singleton](https://cloud.githubusercontent.com/assets/24932090/22450557/cd107460-e7aa-11e6-8f5b-0d4fb0b00fc7.jpg)

변경 전
AppConfigFileLoader aepConfigFileLoader = new AppConfigFileLoader("conf/aep-config.json");
String aepConfigText = aepConfigFileLoader.getText();

변경 후
AppConfigFileLoader appConfigFileLoader = AppConfigFileLoader.getInstance(filePaht);
appConfigFileLoader = appConfigFileLoader.getText();

**Comment by LangVE** [comment]
부모 이슈
issues : https://github.com/YooYoungmo/AEP/issues/3
