### ISSUE TITLE
정적 분석 수행 및 리펙토링 대상 선정 - 3

### ISSUE THREAD

**Issue by YooYoungmo** [YooYoungmo/AEP#19]
정적 분석을 통해 코드 결함을 목록화 하고 이 중 어느 것을 고칠 것인지 대상을 선정 한다.

**Comment by YooYoungmo** [comment]
갖자 2개씩 정해서 가져 오기

**Comment by LangVE** [comment]
* [FindBugs] AppConfigFileLoader.class 의 Dodgy code

**Comment by YooYoungmo** [comment]
- FindBugs - Dodgy Code
![findbugs-1](https://cloud.githubusercontent.com/assets/16472109/22536454/325d202a-e945-11e6-91b6-4f3087e04b79.JPG)

- FindBugs - Multithreaded correctness
![findbugs-2](https://cloud.githubusercontent.com/assets/16472109/22536533/cc9b5c88-e945-11e6-9a9d-81f756c5b36a.JPG)
