### ISSUE TITLE
Disk IO 를 줄이기

### ISSUE THREAD

**Issue by YooYoungmo** [YooYoungmo/AEP#3]
Config 파일 로드 시 [Singleton Pattern](https://en.wikipedia.org/wiki/Singleton_pattern) 적용 하기

**Comment by LangVE** [comment]
이슈 세분화 하여 새로 등록함.
issues : https://github.com/YooYoungmo/AEP/issues/15, https://github.com/YooYoungmo/AEP/issues/16
